import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import Banner from '../components/Banner';
import Videobanner from '../components/Videobanner';
import Circles from '../components/Circles';
import Card from '../components/Card';
import Tourdates from '../components/Tourdates';

const Main = styled.main`
  display: flex;
  //background-color: var(--color-one);
  background-color: rgba(30, 144, 255, 0.22);
  //filter: opacity(0.9);
  align-items: center;
  justify-content: center;
  min-height: 91vh;
  position: relative;
  width: 100%;
  height: 80vh;

  .main-banner {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 95%;
    min-height: 80%;
    //border-radius: 12px;
    border-radius: 50px 170px;
}
  }

  h1,
  p {
    transform: scale(1.4);
    z-index: 1;
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2E4053" />
      </Head>
      <Main>
        <div className="glass main-banner">
          <h1>Music</h1>
          <p>Pagina para probar NextJs</p>
          <Circles />
        </div>
      </Main>
      {/* Seccion con imagenes */}
      <Banner
        title="Banner"
        subtitle="subtitle"
        bgColor="rgba(255, 255, 255, 0.80)"
        cardColor="transparent"
        /* color="white" */
        img=""
      />
      <Videobanner height="75vh">
        <Card />
      </Videobanner>
      <Tourdates bgColor="var(--color-two)" />
    </div>
  );
}
